version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: greencity
    ports:
      - "5432:5432"

  backuser:
    image: greencity-backuser:local
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/greencity
      - DATASOURCE_USER=${POSTGRES_USER}
      - DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - AZURE_CONNECTION_STRING=${AZURE_CONNECTION_STRING}
      - AZURE_CONTAINER_NAME=${AZURE_CONTAINER_NAME}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - PASSWORD_FROM_GMAIL=${PASSWORD_FROM_GMAIL}
    ports:
      - "8060:8060"
    depends_on:
      - db

  backcore:
    image: greencity-backcore:local
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/greencity
      - DATASOURCE_USER=${POSTGRES_USER}
      - DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - AZURE_CONNECTION_STRING=${AZURE_CONNECTION_STRING}
      - AZURE_CONTAINER_NAME=${AZURE_CONTAINER_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: greencity-frontend:local
    ports:
      - "80:80"
    depends_on:
      - backcore
      - backuser